title: Data Portofolio
description: Portofolio of projects involving data analysis.
theme: just-the-docs

url: https://arrafiiqbal.github.io/dataporto

#aux_links: # remove if you don't want this link to appear on your pages
  #Template Repository: https://github.com/YOUR-USERNAME/YOUR-SITE-NAME


plugins:
  - jekyll-default-layout
